### ISSUE TITLE
不支持腾讯视频？

### ISSUE THREAD

**Issue by ivysrono** [LiuLang/monkey-videos#20]
权力的游戏第一季 第01集 - 高清在线观看 - 腾讯视频
http://film.qq.com/cover/s/sfn1vjnjkmzedna.html

**Comment by LiuLang** [comment]
On 03/28/2015 07:31 PM, renyouguo wrote:
> 权力的游戏第一季 第01集 - 高清在线观看 - 腾讯视频
> http://film.qq.com/cover/s/sfn1vjnjkmzedna.html
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/monkey-videos/issues/20
>

是的, 不支持腾迅视频, 暂时也没有这个计划
