### ISSUE TITLE
优酷乐视有的支持有的不支持，还有能不能添加“播放列表直接用mpc打开的功能”？

### ISSUE THREAD

**Issue by easyinplay** [LiuLang/monkey-videos#22]
我一直在用，很感谢你的工作

**Comment by LiuLang** [comment]
On 04/26/2015 01:02 PM, easyinplay wrote:
> 我一直在用，很感谢你的工作
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/monkey-videos/issues/22
>
乐视的是有问题的.

MPC, 我没用过, 不晓得它是否支持播放列表直接打开. 但vlc等常见的播放器是可 
以的.

**Comment by easyinplay** [comment]
Mpc必须把列表下载下来才能打开播放. Vlc在windows上表现不是很好
2015年5月1日 14:08于 "LiuLang" <notifications@github.com>写道：
