### ISSUE TITLE
在FF31.8，油猴0.9.22.1-signed版本下这个脚本不起作用。

### ISSUE THREAD

**Issue by zhangn1985** [LiuLang/monkey-videos#25]

**Comment by zhangn1985** [comment]
FF39也不起作用

**Comment by LiuLang** [comment]
On 07/04/2015 04:28 PM, zhangn1985 wrote:
> FF39也不起作用
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/LiuLang/monkey-videos/issues/25#issuecomment-118484569
>

我在firefox 38.1.0中测试了, 是可以的, Greasemonkey的版本是3.2.
